/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vcsystems.Interfaces;

/**
 *
 * @author mauri
 */
public class menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu.class.getName());

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        SupervisióndeIncidencias = new javax.swing.JButton();
        GestióndeTécnicos = new javax.swing.JButton();
        Reporteyestadísticas = new javax.swing.JButton();
        Aprobaciónderespuestos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Gestióndeusuarios = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(51, 153, 255));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        SupervisióndeIncidencias.setBackground(new java.awt.Color(51, 153, 255));
        SupervisióndeIncidencias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SupervisióndeIncidencias.setForeground(new java.awt.Color(255, 255, 255));
        SupervisióndeIncidencias.setText("Supervisión de Incidencias");
        SupervisióndeIncidencias.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        SupervisióndeIncidencias.setBorderPainted(false);
        SupervisióndeIncidencias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SupervisióndeIncidencias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SupervisióndeIncidencias.setIconTextGap(13);
        SupervisióndeIncidencias.setInheritsPopupMenu(true);
        SupervisióndeIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupervisióndeIncidenciasActionPerformed(evt);
            }
        });

        GestióndeTécnicos.setBackground(new java.awt.Color(51, 153, 255));
        GestióndeTécnicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GestióndeTécnicos.setForeground(new java.awt.Color(255, 255, 255));
        GestióndeTécnicos.setText("Gestión de Técnicos");
        GestióndeTécnicos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        GestióndeTécnicos.setBorderPainted(false);
        GestióndeTécnicos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GestióndeTécnicos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GestióndeTécnicos.setIconTextGap(13);
        GestióndeTécnicos.setInheritsPopupMenu(true);
        GestióndeTécnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestióndeTécnicosActionPerformed(evt);
            }
        });

        Reporteyestadísticas.setBackground(new java.awt.Color(51, 153, 255));
        Reporteyestadísticas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reporteyestadísticas.setForeground(new java.awt.Color(255, 255, 255));
        Reporteyestadísticas.setText("Reporte y estadísticas");
        Reporteyestadísticas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        Reporteyestadísticas.setBorderPainted(false);
        Reporteyestadísticas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Reporteyestadísticas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Reporteyestadísticas.setIconTextGap(13);
        Reporteyestadísticas.setInheritsPopupMenu(true);
        Reporteyestadísticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteyestadísticasActionPerformed(evt);
            }
        });

        Aprobaciónderespuestos.setBackground(new java.awt.Color(51, 153, 255));
        Aprobaciónderespuestos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Aprobaciónderespuestos.setForeground(new java.awt.Color(255, 255, 255));
        Aprobaciónderespuestos.setText("Aprobación de respuestos");
        Aprobaciónderespuestos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        Aprobaciónderespuestos.setBorderPainted(false);
        Aprobaciónderespuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Aprobaciónderespuestos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Aprobaciónderespuestos.setIconTextGap(13);
        Aprobaciónderespuestos.setInheritsPopupMenu(true);
        Aprobaciónderespuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprobaciónderespuestosActionPerformed(evt);
            }
        });

        Gestióndeusuarios.setBackground(new java.awt.Color(51, 153, 255));
        Gestióndeusuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gestióndeusuarios.setForeground(new java.awt.Color(255, 255, 255));
        Gestióndeusuarios.setText("Gestión de usuarios");
        Gestióndeusuarios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        Gestióndeusuarios.setBorderPainted(false);
        Gestióndeusuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Gestióndeusuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Gestióndeusuarios.setIconTextGap(13);
        Gestióndeusuarios.setInheritsPopupMenu(true);
        Gestióndeusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestióndeusuariosActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(51, 153, 255));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("CERRAR SESION");
        btnCerrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btnCerrar.setBorderPainted(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.setIconTextGap(13);
        btnCerrar.setInheritsPopupMenu(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("V&C ");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Gestióndeusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aprobaciónderespuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reporteyestadísticas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GestióndeTécnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupervisióndeIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(SupervisióndeIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GestióndeTécnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gestióndeusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Aprobaciónderespuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reporteyestadísticas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("V&C SYSTEMS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        panelCentral.setBackground(new java.awt.Color(218, 203, 216));
        panelCentral.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Inicio ini = new Inicio();
        ini.setLocationRelativeTo(null);
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void GestióndeusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestióndeusuariosActionPerformed
       panelCentral.removeAll();
    panelCentral.add(new PanelGestionUsuario());
    panelCentral.revalidate();
    panelCentral.repaint();
    }//GEN-LAST:event_GestióndeusuariosActionPerformed

    private void AprobaciónderespuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprobaciónderespuestosActionPerformed
          panelCentral.removeAll();
    panelCentral.add(new PanelAprobacionRepuestos());
    panelCentral.revalidate();
    panelCentral.repaint();
    }//GEN-LAST:event_AprobaciónderespuestosActionPerformed

    private void ReporteyestadísticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteyestadísticasActionPerformed
       panelCentral.removeAll();
    panelCentral.add(new PanelReporteEstadisticas());
    panelCentral.revalidate();
    panelCentral.repaint();

    }//GEN-LAST:event_ReporteyestadísticasActionPerformed

    private void GestióndeTécnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestióndeTécnicosActionPerformed
     panelCentral.removeAll();
    panelCentral.add(new PanelGestionTecnicos());
    panelCentral.revalidate();
    panelCentral.repaint();
    }//GEN-LAST:event_GestióndeTécnicosActionPerformed

    private void SupervisióndeIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupervisióndeIncidenciasActionPerformed
       panelCentral.removeAll();
    panelCentral.add(new PanelSupervision());
    panelCentral.revalidate();
    panelCentral.repaint();
    }//GEN-LAST:event_SupervisióndeIncidenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aprobaciónderespuestos;
    private javax.swing.JButton GestióndeTécnicos;
    private javax.swing.JButton Gestióndeusuarios;
    private javax.swing.JButton Reporteyestadísticas;
    private javax.swing.JButton SupervisióndeIncidencias;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
}
